### ISSUE TITLE
locations within a certain amount of time (ex. 1h)

### ISSUE THREAD

**Issue by tdascoli** [OpendataCH/Transport#106]
is there a possibility to get all locations within a hour of travel time?
example:

from bern all locations within 1h = zurich, basel, biel etc...

**Comment by synox** [comment]
To my knowledge that's currently not possible with the API. I assume it makes more sense to use the static date from http://www.fahrplanfelder.ch/, as for this calculation you don't need the live data. 
There is however a service that offers what you seek for: http://www.arrlee.ch/de/index.html

**Comment by fabian** [comment]
Correct, that's not possible with the Transport API at the moment.
