### ISSUE TITLE
Missing data for stationboard

### ISSUE THREAD

**Issue by STJEREM** [OpendataCH/Transport#108]
In the passlist there is the platform always `"platform":""`and if there is a delay it is still `"delay":null`. Can this be changed? Or is there a different way to access this data?

**Comment by fabian** [comment]
Missing `delay` is also reported in #109

**Comment by fabian** [comment]
I think I found the issue - SBB now often send `StopPrognosis->Arr` because of `handicappedAccess`, that causes problems with the logic in https://github.com/OpendataCH/Transport/blob/9abb57425088061316b6a89889e40787368a4b5f/lib/Transport/Entity/Schedule/Stop.php#L79

**Comment by fabian** [comment]
I think this was fixed in https://github.com/OpendataCH/Transport/commit/ea45e09c532ec425f2a769c571c0cbaf8fa8d7a7 - can anyone confirm?
