### ISSUE TITLE
delay is always null

### ISSUE THREAD

**Issue by janissbinder** [OpendataCH/Transport#109]

**Comment by drasive** [comment]
Just to be clear, do you mean the departure property of the [prognosis object](http://transport.opendata.ch/#prognosis)?

**Comment by STJEREM** [comment]
Yes in `stationboard/stop`, not `stationboard/stop/prognosis`. It is specified how big the delay is when the train leaves, but not how big the delay is when it arrives.

I can send you an example in the next few days. I need a bit time to find an appropriate example.

**Comment by drasive** [comment]
I just thought I found the same issue, I'm not involved in the repo (yet), so don't except too much from me specifically. I'm sure someone trying to find a solution will find an example usefull, though.

**Comment by fabian** [comment]
Closing as duplicate of #108
