### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by sandroroth** [OpendataCH/Transport#116]
The Transport API is currently not working. Even your example request for connections returns an error:
{"errors":[{"message":"Error from fahrplan.sbb.ch: F2 - Spool: Error writing the spoolfile."}]}

The error message is not always the same and sometimes it works.

**Comment by fabian** [comment]
Thanks, I can confirm this problem, experiencing it since yesterday too.

We contacted now SBB to check if they are aware of the problem.

**Comment by fabian** [comment]
Looks like the problem has been fixed.

**Comment by sandroroth** [comment]
Try the example request from the website:
http://transport.opendata.ch/v1/connections?from=Lausanne&to=Genève

The first call was successful, the response of the second call was an error:
{"errors":[{"message":"file_get_contents(http:\/\/fahrplan.sbb.ch\/bin\/extxml.exe\/): failed to open stream: HTTP request failed! "}]}
