### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by awahed** [OpendataCH/Transport#117]
in /locations api, is it possibile to have type=train_stations ? where it shows only train stations near a certain lat & lng such as:

http://transport.opendata.ch/v1/locations?x=46.0051960&y=8.94716308&type=train_stations

thank you very much.

**Comment by hannesgassert** [comment]
@chregu do you have some resources to perhaps look into this?

**Comment by awahed** [comment]
Any update regarding this issue/request ? 
Thank you in advance.

**Comment by fabian** [comment]
I had a quick look and it seems possible with the [`look_stopclass`](https://github.com/OpendataCH/Transport/blob/master/lib/Transport/Entity/Location/NearbyQuery.php#L28) parameter. However the binary seems to be different than what we use in our [Transportations class](https://github.com/OpendataCH/Transport/blob/master/lib/Transport/Entity/Transportations.php).

I will look into implementing this next week.

**Comment by awahed** [comment]
Thank you Fabian.

in /locations api, it would be great if there will be `type=train_stations`, that can be used both when passed `query` or (`x` and `y`) like in examples below.

 -  to show only train stations near a certain lat & lng such as:
   http://transport.opendata.ch/v1/locations?x=46.0051960&y=8.94716308&type=train_stations

 - to list only train stations in an autocomplete field such as:
   http://transport.opendata.ch/v1/locations?query=Basel&type=train_stations

Thank you again.

**Comment by fabian** [comment]
I've implemented the transportations filter now the same way as we already have it for the `/connections` resource. Train stations can now be filtered like this: http://transport.opendata.ch/v1/locations?x=46.0051960&y=8.94716308&transportations[]=ice_tgv_rj&transportations[]=ec_ic&transportations[]=ir&transportations[]=re_d

Unfortunately SBB doesn't provide a similar filtering option for requests with the `query` parameter.
