### ISSUE TITLE
StationBoard API (and probably other) stopped working

### ISSUE THREAD

**Issue by dragoon** [OpendataCH/Transport#118]
I think our **access key** does not work anymore.

**Comment by dragoon** [comment]
Okay it might be that there are simply problems on the backend

**Comment by fabian** [comment]
SBB has confirmed a temporary disruption of fahrplan.sbb.ch. This not only affects the Transport API but also the official SBB mobile app.

I have temporarily reduced the timeout of the Transport API to 10 secs to bring down the server load.

Will update if things come back to normal.

**Comment by fabian** [comment]
Things are back to normal. Timeout of Transport API is set to 60 secs again.

**Comment by dragoon** [comment]
Thanks!
