### ISSUE TITLE
Arrival date bug for trains that arrives after midnight

### ISSUE THREAD

**Issue by awahed** [OpendataCH/Transport#119]
Hi, 
This train ( http://transport.opendata.ch/v1/stationboard?transportations[]=ec_ic&transportations[]=ice_tgv_rj&transportations[]=ir&transportations[]=re_d&transportations[]=s_sn_r&station=Lugano&datetime=2016-01-20T23:57:00&limit=1 ) arrives after midnight.
The arrival time for Bellinzona is shown 2016-01-20T00:26:00+0100 but it should be 21 January.

Thank you in advance in fixing this bug.

**Comment by fabian** [comment]
Thanks for reporting this bug! You are right, the arrival time in `passList` is wrong.

I will try to fix this over the weekend.
