### ISSUE TITLE
different name and number for the same train when calling /connections /stationboard  apis

### ISSUE THREAD

**Issue by awahed** [OpendataCH/Transport#122]
Hi, 

When I call

 /stationboard 

I got this as the information of a train
`name: "S 60",
category: "S",
subcategory: "S",
categoryCode: 5,
number: "60",
operator: "FLP",
to: "Ponte Tresa",`

 /connections

if I call the /connections 
I get the following as the info for the same train 
`journey: {
name: "S 60 22",
category: "S",
subcategory: null,
categoryCode: 5,
number: "22",
operator: "FLP",
to: "Ponte Tresa",`

please notice also the name and number field.

Can you please let me know what is the logic behind this or if it is possibile to fix it. Regards

`http://transport.opendata.ch/v1/connections?direct=1&limit=6&transportations%5B%5D=ec_ic&transportations%5B%5D=ice_tgv_rj&transportations%5B%5D=ir&transportations%5B%5D=re_d&transportations%5B%5D=s_sn_r&from=8505300&to=008505398&date=2016-04-07&time=16%3A20`

`http://transport.opendata.ch/v1/stationboard?transportations%5B%5D=ec_ic&transportations%5B%5D=ice_tgv_rj&transportations%5B%5D=ir&transportations%5B%5D=re_d&transportations%5B%5D=s_sn_r&station=8505391&datetime=2016-04-07+17%3A25`

**Comment by fabian** [comment]
The code responsible for the train information is located in [Journey.php](https://github.com/OpendataCH/Transport/blob/1f16044649545adb8d2a831c4905c2a6d2549022/lib/Transport/Entity/Schedule/Journey.php#L73). As you can see the we don't try to parse the train name/number ourself but just pass the information from SBB on.

A good test is usually also to try the same thing in the official SBB app. Judging from the following screenshots it seems there is some inconsistency in the SBB database with the names "S 60 22" and "S 60":

<img src="https://cloud.githubusercontent.com/assets/13346/14357276/5fc3face-fce8-11e5-8283-c41a68421278.PNG" width="320"> <img src="https://cloud.githubusercontent.com/assets/13346/14357278/61cd10f8-fce8-11e5-8143-e5b1d8e1cde1.PNG" width="320">

Looking at the actual XML response confirms this the value for `<Attribute type="NAME">` differs for the two responses. Here's the relevant part of the response for /connections:

![screenshot 2016-04-07 17 50 53](https://cloud.githubusercontent.com/assets/13346/14357587/91d36a9e-fce9-11e5-996c-06bfe6a74d9e.png)

And here for /stationboard:

![screenshot 2016-04-07 17 51 03](https://cloud.githubusercontent.com/assets/13346/14357595/99c9bf28-fce9-11e5-9e72-389004597749.png)

![screenshot 2016-04-07 17 51 14](https://cloud.githubusercontent.com/assets/13346/14357597/9cd80cd8-fce9-11e5-911a-a9e2b8034b94.png)

Would it help you if we would also parse the `LINE` attribute which would give you the number "60" for the /stationboard? Note that `LINE` would still be missing from /connections.
