### ISSUE TITLE
Regional stations No Work

### ISSUE THREAD

**Issue by PCRefresh** [OpendataCH/Transport#149]
Since yesterday, 12/11/2016, only work the major stations.
All regional stations no longer exist.
why?

Example:
Find: Roma Termini - Is OK
Find: Ciampino - No connections

**Comment by fabian** [comment]
SBB has updated their timetable on 11 December 2016 - I suspect this caused the change.

Can you still find the connection on fahrplan.sbb.ch?

**Comment by PCRefresh** [comment]
Not even works on fahrplan.sbb.ch
Only major stations.

If you try to ask the json from "transport.opendata.ch/v1/stationboard" for small stations you will have the node "stationboard" empty.

This also happens to other European stations.
I tested the "Forest Hill" station (London station) and the problem is present.

This is a real problem. transport OpenData ch is unusable.

**Comment by PCRefresh** [comment]
Now is OK in all stations

**Comment by fabian** [comment]
Great to hear it's okay again! Probably SBB changed something to fix it.
