### ISSUE TITLE
Connections from lat/lon?

### ISSUE THREAD

**Issue by samkass** [OpendataCH/Transport#170]
I'm trying to use this API with a little app that gets the current location in lat/lon and a destination in lat/lon and gets the public transportation options between them. The Location endpoint supports lat/lon, but near as I can figure out, Connections endpoint only supports stations and addresses? I can't even enter "8942 Oberrieden" as an address (I get a null), i have to go down to the street level.

My workaround is to geocode each lat/lon into the nearest street address, format it in a way the API accepts addresses, and send them. I'm sure the server just geocodes it back again, but I don't see another option.

Am I missing something in the API? Is there no way to specify from/to in coordinates?

**Comment by helbling** [comment]
This should work at least in the beta branch, just provide lat,lon wherever you would write a stop or address:
http://transport-beta.opendata.ch/examples/connections.php?from=47.230432%2C8.837132&to=Effretikon&datetime=

**Comment by samkass** [comment]
Ah, thank you, that works great on the beta site. It does not work on the non-beta site, but I guess that shouldn't be a problem soon.
