### ISSUE TITLE
Can't seem to pass transportations to the api

### ISSUE THREAD

**Issue by Carniv0re** [OpendataCH/Transport#188]
I've tried building the url like this: 
`transport.opendata.ch/v1/connections?from=Rapperswil&to=zürich&transportations[]=ship`
I'm building the url from a param dictionary using urllib.parse.urlencode().
but obviously that doesn't work. Do I have to add "ship" to the array of transportations and if so, how do I do that? I don't have much knowledge about dictionaries.
Thanks in advance for your help.

Greetings

**Comment by fabian** [comment]
Sorry, the parameter `transportations` is currently not supported: https://github.com/OpendataCH/Transport/issues/164
