### ISSUE TITLE
Request with isArrivalTime=1 yields connections after the indicated time

### ISSUE THREAD

**Issue by mbeer** [OpendataCH/Transport#198]
The behaviour of requests for connections seems to have changed without notice:

The request https://transport.opendata.ch/v1/connections?from=Luzern&to=Aarau&date=2019-05-22&time=12:00&isArrivalTime=1 gives four connections with arrival times
* `2019-05-22T12:13:00+0200`,
* `2019-05-22T12:30:00+0200`,
* `2019-05-22T12:35:00+0200`, and
* `2019-05-22T12:45:00+0200` 

respectively. These connections all arrive at the destination *after* the requested time. The expected (and former) behaviour was to get connections that arrive *before* the requested time, when `isArrivalTime` is set to `1`.

**Comment by fabian** [comment]
Thanks for the report! There was a recent change at timetable.search.ch which probably caused this, see also https://github.com/OpendataCH/Transport/pull/197.

I think the default logic slightly changed on timetable.search.ch - we now have to use `pre` for page zero and negative.

I've played around with it and I think this should fix it: https://github.com/OpendataCH/Transport/pull/199

If you could check and verify the change it would be appreciated!

**Comment by mbeer** [comment]
Great. This looks fine to me. Thanks.

**Comment by fabian** [comment]
@mbeer Okay, deployed and should be fixed now.
