### ISSUE TITLE
Train / bus numbers: "products" vs "name"

### ISSUE THREAD

**Issue by dbrgn** [OpendataCH/Transport#201]
As discovered in https://github.com/dbrgn/fahrplan/issues/34:

In a connections response, the connection contains sections, which list their bus / train info:

```json
"journey": {
    "name": "M 335",
    "category": "M",
    "subcategory": null,
    "categoryCode": null,
    "number": "m2",
    "operator": "TL",
    "to": "Epalinges, Croisettes",
    ...
```

In this case the name is "M 335" while the number is "m2".

The connection also contains a summary of all used train / bus numbers, which is called "products":

```json
"products": [
    "m2"
],
 ```

As you can see, it uses the numbers instead of the names.

Is that a good choice? If it is, and you decide to stick to it (you may have your reasons) then I'll aggregate the names of the sections, instead of relying on the "products" field. But it may also be a good idea to list the names instead of numbers in "products".

**Comment by dbrgn** [comment]
A similar example which is a bit strange, for the connection from Lausanne to Genève:

"products" is `["IR 15"]`.

The journey object looks like this:

```json
"name": "IR 2522",
"category": "IR",
"subcategory": null,
"categoryCode": null,
"number": "15",
```

Not sure why the name is completely different from the number. Is it the "IR 2522" or the "IR 15"? (I suspect it's the "IR 15 2522", but I have no idea what those numbers mean :slightly_smiling_face:)

**Comment by helbling** [comment]
Well, the different transportation companies sometimes use many different numbers for different things. Not all of which are really important for users. But sometimes they can be useful in combination with other systems.

If you want a user-friendly text you should use the attribute "line" from the timetable.search.ch api (https://oev.search.ch/api/help) which is the API which is used in this project.

**Comment by dbrgn** [comment]
Ok, it seems that `line` maps to `name + " " + number` in the OpendataCH Transport API, right?

**Comment by dbrgn** [comment]
And this is how the "Lausanne to Genève" example is rendered on sbb.ch:

![img](https://tmp.dbrgn.ch/screenshots/20190912092106-yfy666v8.png)

So IR 15 would be the connection and 2510 the exact train.

And the metro example:

![img](https://tmp.dbrgn.ch/screenshots/20190912092353-4i2548na.png)

So maybe the "products" entry in the API should return "M m2" in this case instead of just "m2". But I guess otherwise my question is answered.

Thanks @helbling
