### ISSUE TITLE
Train missed on Stationboard request

### ISSUE THREAD

**Issue by Spillo17** [OpendataCH/Transport#209]
Hi,

since this morning the request for stationboard return not all infos.

For example: 

"stationboard": [
{
"stop": {},
**"name": null,**   
"category": "S",
"subcategory": null,
"categoryCode": null,
"number": "40",
"operator": "SBB",
"to": "Como S. Giovanni",

You can see that the name of the train is missed, I was displayed since 10 today.. it is something changed ?

Thank you

**Comment by helbling** [comment]
What would you expect there?

There was a change in the upstream api which might be related: parameter number is not given anymore, but there is *Z that can be used.
See the example response here:
https://oev.search.ch/api/help#stationboard

**Comment by Spillo17** [comment]
@helbling Thank you... but they change it today.. yesterday it works well... ty for the "workaround"
