### ISSUE TITLE
Searching for only direct connections not working

### ISSUE THREAD

**Issue by nbarrientos** [OpendataCH/Transport#216]
Hi,

The [API documentation](https://transport.opendata.ch/docs.html#connections) states that the `/connections` endpoint accepts a `direct` parameter, described as:

> defaults to 0, if set to 1 only direct connections are allowed

However it does not seem to work as, when passed, connections with transfers are returned.

```
λ curl "http://transport.opendata.ch/v1/connections?from=Meyrin%2C+Hôpital+de+La+Tour&to=Genève-Aéroport%2C+Terminal" | jq | grep transfers
(standard input):      "transfers": 1,
(standard input):      "transfers": 1,
(standard input):      "transfers": 0,
(standard input):      "transfers": 1,
```

```
[~]@outstanding
λ curl "http://transport.opendata.ch/v1/connections?from=Meyrin%2C+Hôpital+de+La+Tour&to=Genève-Aéroport%2C+Terminal&direct=1" | jq | grep transfers
(standard input):      "transfers": 1,
(standard input):      "transfers": 1,
(standard input):      "transfers": 0,
(standard input):      "transfers": 1,
```

Am I doing something wrong?

Thanks.

**Comment by fabian** [comment]
The `direct` parameter is unfortunately not supported by the new backend: https://search.ch/timetable/api/help.en.html

I have removed the unsupported parameters from the documentation.

**Comment by nbarrientos** [comment]
Thanks! So the only way around is to ask for more connections and filter client-side, right?

**Comment by fabian** [comment]
Hmm, yes. Or maybe even consider using the `/stationboard` - but filtering on the client-side is needed in both cases.

**Comment by nbarrientos** [comment]
Merci!
