### ISSUE TITLE
getStationBoard incorrectly adds 1 day (again)

### ISSUE THREAD

**Issue by dragoon** [OpendataCH/Transport#75]
I though I fixed this issue with this commit: 69f7205453e9e47c6718ebce73d4a5e4473c7946 , but this issue with **adding 1 day** actually still persists in one situation:

The problem arises when the train departure is **delayed**. It seems that SBB returns the scheduled departure time, and it could be any time in the past. Don't know how to fix it at the moment.

**Comment by fabian** [comment]
I was now finally able to reproduce this:https://github.com/OpendataCH/Transport/commit/183b8d56d61e4bc3fbd6226a87d19a1fb817fe03#diff-ab3058a49e3328b0fa72c53393127e6eR29

Will implement a solution next week.

**Comment by fabian** [comment]
@dragoon I've implemented now a similar solution as proposed by you, however I realized there's another edge case when the planned departure is before midnight and the delayed departure is after midnight. For that special case there was another fix in `calculateDateTime` needed.

**Comment by dragoon** [comment]
Okay, thanks a lot for figuring this out!
